# .github/workflows/auto-prerelease.yml
name: Release Automatically on tag push
on:
  push:
    tags:
      - v*
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew buildPlugin
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automatic Built Prerelease"
          files: ./build/mirai/*.jar
