# .github/workflows/release-manually.yml
name: Release Manually
permissions: write-all
on:
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        run: |
          echo "$GITHUB_REF"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Test Env
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          [[ ${{ env.RELEASE_VERSION }} == v* ]] || exit 1
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew buildPlugin
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Stable version: ${{ env.RELEASE_VERSION }}"
          files: ./build/mirai/*.jar
